version: 2.1
orbs:
  puppeteer: threetreeslight/puppeteer@0.1.2
  node: circleci/node@2.1.1
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - restore_cache:
        name: Restore Yarn Package Cache
        keys:
          - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Run Tests
          command: yarn test
      - run:
          name: Build Project
          command: yarn build
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
workflows:
    build-and-test:
      jobs:
        - build-and-test